In [1]:
import pandas as pd
import pandas_profiling as pp
import numpy as np

ModuleNotFoundError: No module named 'pandas_profiling'

In [4]:
# read in a May2018 dataset to print columns
May2018 = pd.read_csv('JC-201805-citibike-tripdata.csv')

In [7]:
May2018.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,131,2018-05-01 07:29:57.5490,2018-05-01 07:32:08.6160,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29617,Subscriber,1966,1
1,73,2018-05-01 08:13:58.2560,2018-05-01 08:15:11.9230,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29288,Subscriber,1975,1
2,4929,2018-05-01 08:17:21.3110,2018-05-01 09:39:31.0770,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29520,Customer,1969,0
3,432,2018-05-01 08:25:58.7150,2018-05-01 08:33:10.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29595,Subscriber,1973,1
4,432,2018-05-01 08:28:09.9160,2018-05-01 08:35:22.1440,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,33623,Subscriber,1959,1

In [8]:
June2018 = pd.read_csv('JC-201806-citibike-tripdata.csv')
July2018 = pd.read_csv('JC-201807-citibike-tripdata.csv')
Aug2018 = pd.read_csv('JC-201808-citibike-tripdata.csv')
Sept2018 = pd.read_csv('JC-201809-citibike-tripdata.csv')

In [9]:
frames = [June2018, July2018, Aug2018, Sept2018]
df = pd.concat(frames)
df = df.reset_index()

In [10]:
df.head()

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,329,2018-06-01 07:07:00.2990,2018-06-01 07:12:30.2220,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29513,Subscriber,1991,1
1,1,259,2018-06-01 08:24:43.8490,2018-06-01 08:29:03.8450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26221,Subscriber,1989,2
2,2,686,2018-06-01 09:17:49.5730,2018-06-01 09:29:16.1770,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29266,Subscriber,1990,1
3,3,164,2018-06-01 09:44:00.4020,2018-06-01 09:46:44.6830,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29472,Subscriber,1993,1
4,4,769,2018-06-01 09:59:28.7800,2018-06-01 10:12:18.6660,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33679,Subscriber,1977,1

In [11]:
df = df.reset_index()

In [17]:
df.starttime[0][:10]

'2018-06-01'

In [19]:
df['date'] = [x[:10] for x in df.starttime.values]

In [20]:
df

,level_0,rideid,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,date
0,0,0,329,2018-06-01 07:07:00.2990,2018-06-01 07:12:30.2220,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29513,Subscriber,1991,1,2018-06-01
1,1,1,259,2018-06-01 08:24:43.8490,2018-06-01 08:29:03.8450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26221,Subscriber,1989,2,2018-06-01
2,2,2,686,2018-06-01 09:17:49.5730,2018-06-01 09:29:16.1770,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29266,Subscriber,1990,1,2018-06-01
3,3,3,164,2018-06-01 09:44:00.4020,2018-06-01 09:46:44.6830,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29472,Subscriber,1993,1,2018-06-01
4,4,4,769,2018-06-01 09:59:28.7800,2018-06-01 10:12:18.6660,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33679,Subscriber,1977,1,2018-06-01
5,5,5,256,2018-06-01 10:33:02.1100,2018-06-01 10:37:18.1230,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29269,Subscriber,1984,1,2018-06-01
6,6,6,267,2018-06-01 11:33:22.6440,2018-06-01 11:37:50.0350,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,29551,Subscriber,1988,1,2018-06-01
7,7,7,258,2018-06-01 12:07:49.8830,2018-06-01 12:12:08.0190,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,26271,Subscriber,1976,1,2018-06-01
8,8,8,1247,2018-06-01 12:53:24.8470,2018-06-01 13:14:11.8770,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,30987,Subscriber,1976,1,2018-06-01
9,9,9,761,2018-06-01 13:21:09.2160,2018-06-01 13:33:50.9930,3183,Exchange Place,40.716247,-74.033459,3194,McGinley Square,40.725340,-74.067622,33659,Subscriber,1989,1,2018-06-01
10,10,10,261,2018-06-01 13:29:55.8570,2018-06-01 13:34:17.5260,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26304,Subscriber,1984,1,2018-06-01
11,11,11,294,2018-06-01 13:54:32.1000,2018-06-01 13:59:26.7800,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29523,Subscriber,1990,1,2018-06-01
12,12,12,313,2018-06-01 14:35:06.8030,2018-06-01 14:40:20.3790,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,29299,Subscriber,1978,1,2018-06-01
13,13,13,262,2018-06-01 14:57:34.3880,2018-06-01 15:01:57.2740,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29292,Subscriber,1983,1,2018-06-01
14,14,14,1590,2018-06-01 15:07:33.3550,2018-06-01 15:34:04.2520,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26230,Subscriber,1978,1,2018-06-01
15,15,15,1777,2018-06-01 15:10:55.4010,2018-06-01 15:40:32.5790,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26304,Customer,1969,0,2018-06-01
16,16,16,1747,2018-06-01 15:11:19.1950,2018-06-01 15:40:26.6310,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26277,Customer,1969,0,2018-06-01
17,17,17,872,2018-06-01 15:13:23.3440,2018-06-01 15:27:55.4430,3183,Exchange Place,40.716247,-74.033459,3269,Brunswick & 6th,40.726012,-74.050389,33605,Subscriber,1989,2,2018-06-01
18,18,18,653,2018-06-01 15:29:21.5490,2018-06-01 15:40:15.1570,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,29511,Subscriber,1991,1,2018-06-01
19,19,19,230,2018-06-01 16:09:02.3240,2018-06-01 16:12:52.6560,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33573,Subscriber,1976,1,2018-06-01
20,20,20,307,2018-06-01 16:20:51.7020,2018-06-01 16:25:59.0920,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29472,Subscriber,1986,1,2018-06-01
21,21,21,402,2018-06-01 16:28:53.7800,2018-06-01 16:35:36.6310,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,29299,Subscriber,1971,1,2018-06-01
22,22,22,1489,2018-06-01 16:33:14.4690,2018-06-01 16:58:03.7220,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26304,Customer,1969,0,2018-06-01
23,23,23,1367,2018-06-01 16:35:10.2330,2018-06-01 16:57:57.7810,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29626,Customer,1969,0,2018-06-01
24,24,24,203,2018-06-01 16:35:43.5220,2018-06-01 16:39:06.7080,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,29611,Subscriber,1971,1,2018-06-01
25,25,25,1114,2018-06-01 16:41:27.2570,2018-06-01 17:00:01.3530,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26277,Subscriber,1980,2,2018-06-01
26,26,26,1466,2018-06-01 16:41:40.0020,2018-06-01 17:06:06.0840,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,40.744319,-74.043991,33613,Subscriber,1983,1,2018-06-01
27,27,27,282,2018-06-01 16:47:14.6080,2018-06-01 16:51:56.7830,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33634,Subscriber,1986,1,2018-06-01
28,28,28,1138,2018-06-01 17:04:30.1720,2018-06-01 17:23:28.5080,3183,Exchange Place,40.716247,-74.033459,3195,Sip Ave,40.730743,-74.063784,29514,Subscriber,1987,1,2018-06-01
29,29,29,286,2018-06-01 17:05:27.5510,2018-06-01 17:10:14.4750,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,33682,Subscriber,1987,1,2018-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166629,166629,38992,830,2018-09-22 06:15:38.6820,2018-09-22 06:29:29.5170,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26272,Subscriber,1977,1,2018-09-22
166630,166630,38993,1845,2018-09-22 11:47:16.9400,2018-09-22 12:18:02.0020,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,33665,Subscriber,1987,1,2018-09-22
166631,166631,38994,1501,2018-09-23 08:16:12.4150,2018-09-23 08:41:14.2080,3694,Jackson Square,40.711130,-74.078900,3199,Newport Pkwy,40.728745,-74.032108,33555,Subscriber,1991,2,2018-09-23
166632,166632,38995,3806,2018-09-23 11:11:20.8570,2018-09-23 12:14:47.6670,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29275,Customer,1992,2,2018-09-23
166633,166633,38996,1835,2018-09-23 11:37:17.2500,2018-09-23 12:07:53.1780,3694,Jackson Square,40.711130,-74.078900,3202,Newport PATH,40.727224,-74.033759,26287,Subscriber,1987,1,2018-09-23
166634,166634,38997,913,2018-09-24 06:24:57.1530,2018-09-24 06:40:10.8680,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29271,Subscriber,1977,1,2018-09-24
166635,166635,38998,1026,2018-09-24 07:54:21.7960,2018-09-24 08:11:27.9620,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29674,Subscriber,1987,1,2018-09-24
166636,166636,38999,489,2018-09-24 08:42:25.3530,2018-09-24 08:50:35.2150,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29227,Subscriber,1990,1,2018-09-24
166637,166637,39000,1636,2018-09-24 13:38:49.3530,2018-09-24 14:06:05.9290,3694,Jackson Square,40.711130,-74.078900,3202,Newport PATH,40.727224,-74.033759,26264,Subscriber,1991,2,2018-09-24
166638,166638,39001,969,2018-09-24 13:39:11.0570,2018-09-24 13:55:21.0270,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29677,Subscriber,1988,1,2018-09-24
166639,166639,39002,155507,2018-09-24 15:34:07.6510,2018-09-26 10:45:54.8680,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,33654,Subscriber,1985,2,2018-09-24
166640,166640,39003,407,2018-09-25 09:19:38.5900,2018-09-25 09:26:26.5470,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29575,Subscriber,1990,1,2018-09-25
166641,166641,39004,968,2018-09-25 13:36:04.6410,2018-09-25 13:52:12.6660,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29211,Subscriber,1988,1,2018-09-25
166642,166642,39005,958,2018-09-26 06:16:00.1890,2018-09-26 06:31:58.5360,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29537,Subscriber,1977,1,2018-09-26
166643,166643,39006,1652,2018-09-26 07:17:46.6490,2018-09-26 07:45:18.7540,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,33665,Subscriber,1987,1,2018-09-26
166644,166644,39007,448,2018-09-26 08:52:47.0060,2018-09-26 09:00:15.5720,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29626,Subscriber,1990,1,2018-09-26
166645,166645,39008,1001,2018-09-26 13:40:23.1630,2018-09-26 13:57:04.6890,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29619,Subscriber,1988,1,2018-09-26
166646,166646,39009,800,2018-09-26 16:43:45.5680,2018-09-26 16:57:06.5360,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26184,Subscriber,1964,1,2018-09-26
166647,166647,39010,403,2018-09-27 06:22:42.5670,2018-09-27 06:29:25.7660,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29302,Subscriber,1990,1,2018-09-27
166648,166648,39011,1029,2018-09-27 10:19:02.5110,2018-09-27 10:36:12.1520,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29569,Subscriber,1987,1,2018-09-27
166649,166649,39012,529,2018-09-27 11:06:43.6100,2018-09-27 11:15:33.5520,3694,Jackson Square,40.711130,-74.078900,3191,Union St,40.718211,-74.083639,29552,Subscriber,1994,2,2018-09-27
166650,166650,39013,70560,2018-09-27 15:32:03.6860,2018-09-28 11:08:04.1010,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26161,Subscriber,1985,2,2018-09-27
166651,166651,39014,998,2018-09-28 08:50:31.7080,2018-09-28 09:07:09.7350,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,33653,Subscriber,1987,1,2018-09-28
166652,166652,39015,740,2018-09-29 06:17:22.5580,2018-09-29 06:29:43.3150,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26706,Subscriber,1977,1,2018-09-29
166653,166653,39016,555,2018-09-29 08:53:37.1210,2018-09-29 09:02:53.0450,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29447,Subscriber,1990,1,2018-09-29
166654,166654,39017,985,2018-09-29 09:02:31.3090,2018-09-29 09:18:56.6570,3694,Jackson Square,40.711130,-74.078900,3211,Newark Ave,40.721525,-74.046305,29492,Subscriber,1991,2,2018-09-29
166655,166655,39018,1595,2018-09-30 09:36:44.8650,2018-09-30 10:03:19.9750,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29252,Subscriber,1987,1,2018-09-30
166656,166656,39019,1996,2018-09-30 11:15:46.8100,2018-09-30 11:49:03.1200,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29122,Customer,1987,2,2018-09-30
166657,166657,39020,1803,2018-09-30 11:16:37.0760,2018-09-30 11:46:40.6460,3694,Jackson Square,40.711130,-74.078900,3273,Manila & 1st,40.721651,-74.042884,29251,Customer,1974,1,2018-09-30
166658,166658,39021,779,2018-09-30 13:49:47.3930,2018-09-30 14:02:46.7200,3694,Jackson Square,40.711130,-74.078900,3192,Liberty Light Rail,40.711242,-74.055701,29653,Customer,1969,0,2018-09-30

In [22]:
df = df.rename(columns={'index': 'rideid'})
df.to_csv('citibike.csv', index=False)